"""Add agent tasks table

Revision ID: b2f4ae3e874d
Revises: 001_initial
Create Date: 2025-12-30 00:44:19.281240+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2f4ae3e874d"
down_revision: Union[str, None] = "001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operation_logs",
        "file_path",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_operation_logs_user_id"), "operation_logs", ["user_id"], unique=False)
    op.drop_index("ix_users_email", table_name="users")
    op.drop_constraint("uq_users_github_id", "users", type_="unique")
    op.drop_constraint("uq_users_github_username", "users", type_="unique")
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.create_unique_constraint("uq_users_github_username", "users", ["github_username"])
    op.create_unique_constraint("uq_users_github_id", "users", ["github_id"])
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.drop_index(op.f("ix_operation_logs_user_id"), table_name="operation_logs")
    op.alter_column(
        "operation_logs",
        "file_path",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
