"""Add environment_variables table

Revision ID: adafc1b64587
Revises: 20260126_000000
Create Date: 2026-01-28 06:45:42.526377+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adafc1b64587"
down_revision: Union[str, None] = "20260126_000000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_messages_session_created", table_name="chat_messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_chat_messages_session_created",
        "chat_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
