"""Add backend_connections and project_backend_configs tables

Revision ID: a2306eab695e
Revises: 66fb00855a8b
Create Date: 2026-01-02 08:22:19.627389+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2306eab695e"
down_revision: Union[str, None] = "66fb00855a8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
