"""Add multi-platform fields

Revision ID: 66fb00855a8b
Revises: 20251230_192600_update_enums
Create Date: 2026-01-02 07:40:01.598811+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "66fb00855a8b"
down_revision: Union[str, None] = "20251230_192600_update_enums"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operation_logs",
        "operation_type",
        existing_type=postgresql.ENUM(
            "file_created",
            "file_updated",
            "file_deleted",
            "branch_created",
            "commit_created",
            "push_completed",
            "pr_created",
            "pr_merged",
            "build_started",
            "build_progress",
            "build_completed",
            "build_failed",
            "deployment_started",
            "deployment_completed",
            "deployment_failed",
            "code_review_started",
            "code_review_completed",
            "code_review_issue",
            "agent_task_started",
            "agent_task_completed",
            "agent_task_failed",
            "plan_created",
            "plan_step_started",
            "plan_step_completed",
            "project_created",
            "project_updated",
            "project_archived",
            "user_message",
            "agent_response",
            "file_read",
            name="operationtype",
        ),
        type_=sa.Enum(
            "agent_task_started",
            "agent_task_completed",
            "agent_task_failed",
            "plan_created",
            "plan_step_started",
            "plan_step_completed",
            "file_read",
            "file_created",
            "file_updated",
            "file_deleted",
            "code_review_started",
            "code_review_completed",
            "code_review_issue",
            "branch_created",
            "commit_created",
            "push_completed",
            "pr_created",
            "pr_merged",
            "build_started",
            "build_progress",
            "build_completed",
            "build_failed",
            "deployment_started",
            "deployment_completed",
            "deployment_failed",
            "project_created",
            "project_updated",
            "project_archived",
            "user_message",
            "agent_response",
            name="operationtype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "operation_logs",
        "agent_type",
        existing_type=postgresql.ENUM(
            "planner",
            "flutter_engineer",
            "code_reviewer",
            "git_operator",
            "build_deploy",
            "memory",
            "system",
            "backend_engineer",
            "user",
            name="agenttype",
        ),
        type_=sa.Enum(
            "planner",
            "flutter_engineer",
            "code_reviewer",
            "git_operator",
            "build_deploy",
            "memory",
            "backend_engineer",
            "system",
            "user",
            name="agenttype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.add_column("projects", sa.Column("platform_type", sa.String(length=50), nullable=True))
    op.add_column("projects", sa.Column("framework", sa.String(length=50), nullable=True))
    op.add_column("projects", sa.Column("backend_type", sa.String(length=50), nullable=True))
    op.add_column("projects", sa.Column("backend_config", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("deployment_platform", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_projects_framework"), "projects", ["framework"], unique=False)
    op.create_index(op.f("ix_projects_platform_type"), "projects", ["platform_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_platform_type"), table_name="projects")
    op.drop_index(op.f("ix_projects_framework"), table_name="projects")
    op.drop_column("projects", "deployment_platform")
    op.drop_column("projects", "backend_config")
    op.drop_column("projects", "backend_type")
    op.drop_column("projects", "framework")
    op.drop_column("projects", "platform_type")
    op.alter_column(
        "operation_logs",
        "agent_type",
        existing_type=sa.Enum(
            "planner",
            "flutter_engineer",
            "code_reviewer",
            "git_operator",
            "build_deploy",
            "memory",
            "backend_engineer",
            "system",
            "user",
            name="agenttype",
            native_enum=False,
        ),
        type_=postgresql.ENUM(
            "planner",
            "flutter_engineer",
            "code_reviewer",
            "git_operator",
            "build_deploy",
            "memory",
            "system",
            "backend_engineer",
            "user",
            name="agenttype",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "operation_logs",
        "operation_type",
        existing_type=sa.Enum(
            "agent_task_started",
            "agent_task_completed",
            "agent_task_failed",
            "plan_created",
            "plan_step_started",
            "plan_step_completed",
            "file_read",
            "file_created",
            "file_updated",
            "file_deleted",
            "code_review_started",
            "code_review_completed",
            "code_review_issue",
            "branch_created",
            "commit_created",
            "push_completed",
            "pr_created",
            "pr_merged",
            "build_started",
            "build_progress",
            "build_completed",
            "build_failed",
            "deployment_started",
            "deployment_completed",
            "deployment_failed",
            "project_created",
            "project_updated",
            "project_archived",
            "user_message",
            "agent_response",
            name="operationtype",
            native_enum=False,
        ),
        type_=postgresql.ENUM(
            "file_created",
            "file_updated",
            "file_deleted",
            "branch_created",
            "commit_created",
            "push_completed",
            "pr_created",
            "pr_merged",
            "build_started",
            "build_progress",
            "build_completed",
            "build_failed",
            "deployment_started",
            "deployment_completed",
            "deployment_failed",
            "code_review_started",
            "code_review_completed",
            "code_review_issue",
            "agent_task_started",
            "agent_task_completed",
            "agent_task_failed",
            "plan_created",
            "plan_step_started",
            "plan_step_completed",
            "project_created",
            "project_updated",
            "project_archived",
            "user_message",
            "agent_response",
            "file_read",
            name="operationtype",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
