"""Add implementation plans and tasks

Revision ID: d6ee6fa321db
Revises: c2d03f48b921
Create Date: 2026-01-12 19:04:38.634045+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6ee6fa321db"
down_revision: Union[str, None] = "c2d03f48b921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "implementation_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("user_request", sa.Text(), nullable=False),
        sa.Column("markdown_content", sa.Text(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("walkthrough_path", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending_review",
                "approved",
                "rejected",
                "in_progress",
                "completed",
                "failed",
                name="planstatus",
            ),
            nullable=False,
        ),
        sa.Column("estimated_time", sa.String(length=50), nullable=True),
        sa.Column("total_tasks", sa.Integer(), nullable=False),
        sa.Column("completed_tasks", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_implementation_plans_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_implementation_plans")),
    )
    op.create_index(
        op.f("ix_implementation_plans_project_id"),
        "implementation_plans",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_implementation_plans_status"), "implementation_plans", ["status"], unique=False
    )
    op.create_table(
        "plan_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["implementation_plans.id"],
            name=op.f("fk_plan_tasks_plan_id_implementation_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_tasks")),
    )
    op.create_index(op.f("ix_plan_tasks_plan_id"), "plan_tasks", ["plan_id"], unique=False)
    # Commented out: agent_tasks table doesn't exist in migration chain
    # op.drop_column("agent_tasks", "current_agent")
    op.alter_column(
        "operation_logs",
        "operation_type",
        existing_type=sa.VARCHAR(length=21),
        type_=sa.Enum(
            "agent_started",
            "agent_completed",
            "agent_failed",
            "tool_execution",
            "file_read",
            "file_created",
            "file_updated",
            "file_deleted",
            "commit_created",
            "build_started",
            "build_completed",
            "build_failed",
            "deployment_started",
            "deployment_completed",
            "deployment_failed",
            "project_created",
            "project_updated",
            "user_message",
            "agent_response",
            name="operationtype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "operation_logs",
        "agent_type",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum("codi", "system", "user", name="agenttype", native_enum=False),
        existing_nullable=False,
    )
    op.drop_index("ix_projects_github_repo_full_name", table_name="projects")
    op.drop_column("projects", "github_repo_full_name")
    op.drop_column("projects", "github_clone_url")
    op.drop_column("projects", "github_repo_name")
    op.drop_column("projects", "github_repo_url")
    op.drop_column("projects", "github_default_branch")
    op.drop_column("projects", "github_current_branch")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "github_current_branch", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "github_default_branch", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "projects",
        sa.Column("github_repo_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("github_repo_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("github_clone_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column(
            "github_repo_full_name", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        "ix_projects_github_repo_full_name", "projects", ["github_repo_full_name"], unique=False
    )
    op.alter_column(
        "operation_logs",
        "agent_type",
        existing_type=sa.Enum("codi", "system", "user", name="agenttype", native_enum=False),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "operation_logs",
        "operation_type",
        existing_type=sa.Enum(
            "agent_started",
            "agent_completed",
            "agent_failed",
            "tool_execution",
            "file_read",
            "file_created",
            "file_updated",
            "file_deleted",
            "commit_created",
            "build_started",
            "build_completed",
            "build_failed",
            "deployment_started",
            "deployment_completed",
            "deployment_failed",
            "project_created",
            "project_updated",
            "user_message",
            "agent_response",
            name="operationtype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=21),
        existing_nullable=False,
    )
    # Commented out: agent_tasks table doesn't exist in migration chain
    # op.add_column(
    #     "agent_tasks",
    #     sa.Column("current_agent", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # )
    op.drop_index(op.f("ix_plan_tasks_plan_id"), table_name="plan_tasks")
    op.drop_table("plan_tasks")
    op.drop_index(op.f("ix_implementation_plans_status"), table_name="implementation_plans")
    op.drop_index(op.f("ix_implementation_plans_project_id"), table_name="implementation_plans")
    op.drop_table("implementation_plans")
    # ### end Alembic commands ###
