"""Agent task database model."""
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.project import Project


class AgentTask(Base):
    """Agent task model for tracking agent workflow execution."""

    __tablename__ = "agent_tasks"

    # Primary key (string ID generated by API)
    id: Mapped[str] = mapped_column(String(50), primary_key=True)

    # Foreign keys
    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    project_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Task details
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="queued"
    )  # queued, processing, completed, failed
    message: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Execution metadata
    current_agent: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    progress: Mapped[float] = mapped_column(Integer, default=0) # 0 to 100
    
    # Results and errors
    result: Mapped[Optional[dict[str, Any]]] = mapped_column(JSONB, nullable=True)
    error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    user: Mapped["User"] = relationship("User", lazy="selectin")
    project: Mapped["Project"] = relationship("Project", lazy="selectin")

    def __repr__(self) -> str:
        """String representation of AgentTask."""
        return f"<AgentTask(id={self.id}, status={self.status})>"

    def to_dict(self) -> dict:
        """Convert agent task to dictionary."""
        return {
            "task_id": self.id,
            "project_id": self.project_id,
            "user_id": self.user_id,
            "status": self.status,
            "message": self.message,
            "current_agent": self.current_agent,
            "progress": self.progress / 100.0 if self.progress is not None else 0.0,
            "result": self.result,
            "error": self.error,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
        }
