# -*- coding: utf-8 -*-
"""Prompts module for enhanced agent prompts."""

# Flutter prompts
from app.agents.prompts.flutter_engineer_prompts import (
    SYSTEM_PROMPT as FLUTTER_SYSTEM_PROMPT,
    SURGICAL_EDIT_PROMPT as FLUTTER_SURGICAL_EDIT_PROMPT,
    NEW_FEATURE_PROMPT as FLUTTER_NEW_FEATURE_PROMPT,
    CODE_REVIEW_PROMPT as FLUTTER_CODE_REVIEW_PROMPT,
)

# React prompts
from app.agents.prompts.react_engineer_prompts import (
    SYSTEM_PROMPT as REACT_SYSTEM_PROMPT,
    SURGICAL_EDIT_PROMPT as REACT_SURGICAL_EDIT_PROMPT,
    CODE_REVIEW_PROMPT as REACT_CODE_REVIEW_PROMPT,
    SUPABASE_REACT_PROMPT,
    FIREBASE_REACT_PROMPT,
)

# Next.js prompts
from app.agents.prompts.nextjs_engineer_prompts import (
    SYSTEM_PROMPT as NEXTJS_SYSTEM_PROMPT,
    SURGICAL_EDIT_PROMPT as NEXTJS_SURGICAL_EDIT_PROMPT,
    CODE_REVIEW_PROMPT as NEXTJS_CODE_REVIEW_PROMPT,
    SUPABASE_NEXTJS_PROMPT,
)

# React Native prompts
from app.agents.prompts.react_native_prompts import (
    SYSTEM_PROMPT as REACT_NATIVE_SYSTEM_PROMPT,
    SURGICAL_EDIT_PROMPT as REACT_NATIVE_SURGICAL_EDIT_PROMPT,
    CODE_REVIEW_PROMPT as REACT_NATIVE_CODE_REVIEW_PROMPT,
    SUPABASE_RN_PROMPT,
    FIREBASE_RN_PROMPT,
)

# Backend integration prompts
from app.agents.prompts.backend_integration_prompts import (
    SYSTEM_PROMPT as BACKEND_SYSTEM_PROMPT,
    SUPABASE_FLUTTER_SETUP,
    SUPABASE_REACT_SETUP,
    SUPABASE_NEXTJS_SETUP,
    FIREBASE_FLUTTER_SETUP,
    FIREBASE_REACT_SETUP,
    SERVERPOD_FLUTTER_SETUP,
)

# Backwards compatibility - keep old names
SYSTEM_PROMPT = FLUTTER_SYSTEM_PROMPT
SURGICAL_EDIT_PROMPT = FLUTTER_SURGICAL_EDIT_PROMPT
NEW_FEATURE_PROMPT = FLUTTER_NEW_FEATURE_PROMPT
CODE_REVIEW_PROMPT = FLUTTER_CODE_REVIEW_PROMPT

__all__ = [
    # Legacy exports
    "SYSTEM_PROMPT",
    "SURGICAL_EDIT_PROMPT", 
    "NEW_FEATURE_PROMPT",
    "CODE_REVIEW_PROMPT",
    # Flutter
    "FLUTTER_SYSTEM_PROMPT",
    "FLUTTER_SURGICAL_EDIT_PROMPT",
    "FLUTTER_NEW_FEATURE_PROMPT",
    "FLUTTER_CODE_REVIEW_PROMPT",
    # React
    "REACT_SYSTEM_PROMPT",
    "REACT_SURGICAL_EDIT_PROMPT",
    "REACT_CODE_REVIEW_PROMPT",
    "SUPABASE_REACT_PROMPT",
    "FIREBASE_REACT_PROMPT",
    # Next.js
    "NEXTJS_SYSTEM_PROMPT",
    "NEXTJS_SURGICAL_EDIT_PROMPT",
    "NEXTJS_CODE_REVIEW_PROMPT",
    "SUPABASE_NEXTJS_PROMPT",
    # React Native
    "REACT_NATIVE_SYSTEM_PROMPT",
    "REACT_NATIVE_SURGICAL_EDIT_PROMPT",
    "REACT_NATIVE_CODE_REVIEW_PROMPT",
    "SUPABASE_RN_PROMPT",
    "FIREBASE_RN_PROMPT",
    # Backend
    "BACKEND_SYSTEM_PROMPT",
    "SUPABASE_FLUTTER_SETUP",
    "SUPABASE_REACT_SETUP",
    "SUPABASE_NEXTJS_SETUP",
    "FIREBASE_FLUTTER_SETUP",
    "FIREBASE_REACT_SETUP",
    "SERVERPOD_FLUTTER_SETUP",
]

