# -*- coding: utf-8 -*-
"""Backend Integration Agent prompts for Supabase, Firebase, and Serverpod."""

SYSTEM_PROMPT = """You are an EXPERT Backend Integration Engineer.

Your role is to set up and configure backend services (Supabase, Firebase, Serverpod)
for web and mobile applications.

SUPPORTED BACKENDS:
1. Supabase - PostgreSQL, Auth, Realtime, Storage
2. Firebase - Firestore, Auth, FCM, Storage
3. Serverpod - Dart backend, PostgreSQL, WebSockets

ENVIRONMENT VARIABLE PATTERNS:
```bash
# Supabase
SUPABASE_URL=https://xxx.supabase.co
SUPABASE_ANON_KEY=eyJhbG...
SUPABASE_SERVICE_KEY=eyJhbG... # Optional, server-side only

# Firebase Web
FIREBASE_API_KEY=AIzaSy...
FIREBASE_AUTH_DOMAIN=myapp.firebaseapp.com
FIREBASE_PROJECT_ID=myapp-12345
FIREBASE_STORAGE_BUCKET=myapp-12345.appspot.com
FIREBASE_MESSAGING_SENDER_ID=123456789
FIREBASE_APP_ID=1:123456789:web:abc123

# Serverpod
SERVERPOD_URL=https://api.myapp.com
DATABASE_URL=postgresql://user:pass@host:5432/db
```

SECURITY RULES:
1. NEVER hardcode API keys in code
2. Use environment variables for ALL secrets
3. Validate all user input on the server
4. Use Row Level Security (RLS) in Supabase
5. Use Security Rules in Firebase
6. Implement proper auth checks

YOUR CODE MUST BE SECURE AND FOLLOW BEST PRACTICES.
"""

# Supabase Setup Prompts
SUPABASE_FLUTTER_SETUP = """Setup Supabase for Flutter:

```dart
// lib/core/supabase_client.dart
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

class SupabaseService {
  static SupabaseClient get client => Supabase.instance.client;
  
  static Future<void> init() async {
    await Supabase.initialize(
      url: dotenv.env['SUPABASE_URL'] ?? '',
      anonKey: dotenv.env['SUPABASE_ANON_KEY'] ?? '',
    );
  }
  
  // Auth
  static Future<AuthResponse> signIn(String email, String password) async {
    return await client.auth.signInWithPassword(email: email, password: password);
  }
  
  static Future<AuthResponse> signUp(String email, String password) async {
    return await client.auth.signUp(email: email, password: password);
  }
  
  static Future<void> signOut() async {
    await client.auth.signOut();
  }
  
  static User? get currentUser => client.auth.currentUser;
  
  static Stream<AuthState> get authStateChanges => client.auth.onAuthStateChange;
}
```

```dart
// main.dart
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:codi/core/supabase_client.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: '.env');
  await SupabaseService.init();
  runApp(const MyApp());
}
```

```yaml
# pubspec.yaml dependencies
dependencies:
  supabase_flutter: ^2.3.0
  flutter_dotenv: ^5.1.0
```
"""

SUPABASE_REACT_SETUP = """Setup Supabase for React:

```typescript
// lib/supabase.ts
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
```

```typescript
// hooks/useAuth.ts
import { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';
import type { User } from '@supabase/supabase-js';

export function useAuth() {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUser(session?.user ?? null);
      setLoading(false);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      (_event, session) => { setUser(session?.user ?? null); }
    );

    return () => subscription.unsubscribe();
  }, []);

  return { user, loading };
}
```
"""

SUPABASE_NEXTJS_SETUP = """Setup Supabase for Next.js App Router:

```typescript
// lib/supabase/server.ts
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';

export function createClient() {
  const cookieStore = cookies();
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name) { return cookieStore.get(name)?.value; },
        set(name, value, options) { cookieStore.set({ name, value, ...options }); },
        remove(name, options) { cookieStore.set({ name, value: '', ...options }); },
      },
    }
  );
}
```

```typescript
// lib/supabase/client.ts
import { createBrowserClient } from '@supabase/ssr';

export function createClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}
```
"""

# Firebase Setup Prompts
FIREBASE_FLUTTER_SETUP = """Setup Firebase for Flutter:

```dart
// lib/firebase_options.dart (generated by flutterfire configure)
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Platform-specific options
  }
}
```

```dart
// lib/core/firebase_service.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../firebase_options.dart';

class FirebaseService {
  static final FirebaseAuth _auth = FirebaseAuth.instance;
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  
  static Future<void> init() async {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  }
  
  static User? get currentUser => _auth.currentUser;
  static Stream<User?> get authStateChanges => _auth.authStateChanges();
  
  static Future<UserCredential> signIn(String email, String password) async {
    return await _auth.signInWithEmailAndPassword(email: email, password: password);
  }
  
  static Future<UserCredential> signUp(String email, String password) async {
    return await _auth.createUserWithEmailAndPassword(email: email, password: password);
  }
  
  static Future<void> signOut() async {
    await _auth.signOut();
  }
  
  static CollectionReference collection(String path) => _firestore.collection(path);
}
```

```yaml
# pubspec.yaml
dependencies:
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
```
"""

FIREBASE_REACT_SETUP = """Setup Firebase for React:

```typescript
// lib/firebase.ts
import { initializeApp, getApps } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
};

const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApps()[0];
export const auth = getAuth(app);
export const db = getFirestore(app);
```
"""

# Serverpod Setup Prompts
SERVERPOD_FLUTTER_SETUP = """Setup Serverpod for Flutter:

```dart
// lib/core/serverpod_client.dart
import 'package:serverpod_client/serverpod_client.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

class ServerpodService {
  static late Client client;
  
  static Future<void> init() async {
    final serverUrl = dotenv.env['SERVERPOD_URL'] ?? 'http://localhost:8080';
    client = Client(serverUrl);
  }
}
```

```yaml
# pubspec.yaml
dependencies:
  serverpod_client: ^1.2.0
  flutter_dotenv: ^5.1.0
```
"""

DATABASE_SCHEMA_PROMPT = """Create database schema:

USER REQUEST: {user_request}
BACKEND: {backend_type}
TABLES: {tables}

For Supabase, generate:
1. SQL migration file
2. TypeScript types (database.types.ts)
3. Row Level Security policies

For Firebase, generate:
1. Firestore security rules
2. TypeScript types

For Serverpod, generate:
1. Protocol files (.yaml)
2. Dart models
"""

CODE_REVIEW_PROMPT = """Review backend integration code:

CHECKLIST:
□ No hardcoded secrets
□ Environment variables used correctly
□ Auth checks implemented
□ Input validation present
□ Error handling complete
□ Security rules configured

CODE:
```
{code}
```

Return JSON:
{{
  "approved": true/false,
  "security_issues": [],
  "errors": []
}}

REJECT if ANY security issue found.
"""
