"""Service for managing environment variables."""
import os
from pathlib import Path
from typing import Dict, List, Optional

from app.models.environment_variable import EnvironmentVariable
from app.models.project import Project
from app.utils.logging import get_logger

logger = get_logger(__name__)


class EnvironmentService:
    """Service for managing project environment variables."""

    # Default environment variables for different project types
    SERVERPOD_DEFAULTS = {
        "PROJECT_NAME": {"value": "", "context": "docker-compose", "description": "Project name used for container naming"},
        "ENVIRONMENT": {"value": "development", "context": "docker-compose", "description": "Environment mode (development/production)"},
        "DB_PASSWORD": {"value": "dev_password_change_in_prod", "context": "docker-compose", "description": "PostgreSQL database password", "is_secret": True},
        "POSTGRES_PORT": {"value": "5432", "context": "docker-compose", "description": "PostgreSQL port"},
        "REDIS_PORT": {"value": "6379", "context": "docker-compose", "description": "Redis port"},
        "SERVERPOD_PORT": {"value": "8080", "context": "docker-compose", "description": "Serverpod API port"},
        "SERVERPOD_INSIGHTS_PORT": {"value": "8081", "context": "docker-compose", "description": "Serverpod Insights UI port"},
        "FLUTTER_PORT": {"value": "3000", "context": "docker-compose", "description": "Flutter web app port"},
    }

    @staticmethod
    def generate_env_file_content(
        variables: List[EnvironmentVariable],
        context: Optional[str] = None,
        include_secrets: bool = True,
    ) -> str:
        """Generate .env file content from environment variables.
        
        Args:
            variables: List of environment variables
            context: Filter by context (None for all)
            include_secrets: Whether to include secret values
            
        Returns:
            .env file content as string
        """
        lines = ["# Auto-generated by Codi Environment Manager", ""]
        
        # Group by context
        by_context: Dict[str, List[EnvironmentVariable]] = {}
        for var in variables:
            if context and var.context != context:
                continue
            if var.context not in by_context:
                by_context[var.context] = []
            by_context[var.context].append(var)
        
        # Generate content
        for ctx in sorted(by_context.keys()):
            lines.append(f"# {ctx.upper()} Variables")
            for var in sorted(by_context[ctx], key=lambda v: v.key):
                if var.description:
                    lines.append(f"# {var.description}")
                
                if var.is_secret and not include_secrets:
                    lines.append(f"{var.key}=***")
                else:
                    value = var.get_value()
                    # Escape special characters in value
                    if " " in value or any(c in value for c in ['$', '"', "'"]):
                        # Quote the value
                        value = value.replace('"', '\\"')
                        lines.append(f'{var.key}="{value}"')
                    else:
                        lines.append(f"{var.key}={value}")
            lines.append("")
        
        return "\n".join(lines)

    @staticmethod
    def parse_env_file(file_path: str) -> Dict[str, str]:
        """Parse .env file into key-value pairs.
        
        Args:
            file_path: Path to .env file
            
        Returns:
            Dictionary of environment variables
        """
        env_vars = {}
        
        if not os.path.exists(file_path):
            return env_vars
        
        with open(file_path, 'r') as f:
            for line in f:
                line = line.strip()
                # Skip empty lines and comments
                if not line or line.startswith('#'):
                    continue
                
                # Parse KEY=VALUE
                if '=' in line:
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip()
                    
                    # Remove quotes from value if present
                    if value.startswith('"') and value.endswith('"'):
                        value = value[1:-1].replace('\\"', '"')
                    elif value.startswith("'") and value.endswith("'"):
                        value = value[1:-1]
                    
                    env_vars[key] = value
        
        return env_vars

    @staticmethod
    def sync_to_file(
        project: Project,
        variables: List[EnvironmentVariable],
        context: Optional[str] = None,
        include_secrets: bool = True,
    ) -> str:
        """Sync environment variables to project's .env file.
        
        Args:
            project: Project instance
            variables: List of environment variables
            context: Filter by context
            include_secrets: Whether to include secret values
            
        Returns:
            Path to the created .env file
        """
        if not project.local_path:
            raise ValueError("Project has no local path")
        
        project_path = Path(project.local_path)
        env_file = project_path / ".env"
        
        # Generate content
        content = EnvironmentService.generate_env_file_content(
            variables, context=context, include_secrets=include_secrets
        )
        
        # Write to file
        env_file.write_text(content)
        logger.info(f"Synced {len(variables)} environment variables to {env_file}")
        
        return str(env_file)

    @staticmethod
    def get_defaults_for_project(project: Project) -> Dict[str, Dict[str, any]]:
        """Get default environment variables for a project type.
        
        Args:
            project: Project instance
            
        Returns:
            Dictionary of default variables with metadata
        """
        if project.backend_type == "serverpod":
            defaults = EnvironmentService.SERVERPOD_DEFAULTS.copy()
            # Set PROJECT_NAME to actual project name
            project_slug = Path(project.local_path).name if project.local_path else project.name
            defaults["PROJECT_NAME"]["value"] = project_slug
            return defaults
        
        # For other project types, return minimal defaults
        return {
            "ENVIRONMENT": {"value": "development", "context": "general", "description": "Environment mode"},
        }

    @staticmethod
    def ensure_defaults(project: Project, variables: List[EnvironmentVariable]) -> List[EnvironmentVariable]:
        """Ensure default environment variables exist for a project.
        
        Args:
            project: Project instance
            variables: Existing environment variables
            
        Returns:
            List of variables that were added (new defaults)
        """
        existing_keys = {var.key for var in variables}
        defaults = EnvironmentService.get_defaults_for_project(project)
        
        new_variables = []
        for key, config in defaults.items():
            if key not in existing_keys:
                var = EnvironmentVariable(
                    project_id=project.id,
                    key=key,
                    context=config.get("context", "general"),
                    description=config.get("description"),
                )
                var.set_value(config["value"], is_secret=config.get("is_secret", False))
                new_variables.append(var)
        
        return new_variables
